package com.pipegrid.model;

// Generated Aug 24, 2012 4:44:03 PM by Hibernate Tools 4.0.0

/**
 * CompanyClassifications generated by hbm2java
 */
public class CompanyClassifications implements java.io.Serializable {

	private CompanyClassificationsId id;
	private Company company;
	private CompanyClassificationLkup companyClassificationLkup;

	public CompanyClassifications() {
	}

	public CompanyClassifications(CompanyClassificationsId id, Company company,
			CompanyClassificationLkup companyClassificationLkup) {
		this.id = id;
		this.company = company;
		this.companyClassificationLkup = companyClassificationLkup;
	}

	public CompanyClassificationsId getId() {
		return this.id;
	}

	public void setId(CompanyClassificationsId id) {
		this.id = id;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public CompanyClassificationLkup getCompanyClassificationLkup() {
		return this.companyClassificationLkup;
	}

	public void setCompanyClassificationLkup(
			CompanyClassificationLkup companyClassificationLkup) {
		this.companyClassificationLkup = companyClassificationLkup;
	}

}
