package com.pipegrid.model;

// Generated Aug 24, 2012 4:44:03 PM by Hibernate Tools 4.0.0

/**
 * CompanyClassificationsId generated by hbm2java
 */
public class CompanyClassificationsId implements java.io.Serializable {

	private long companyId;
	private short classificationId;

	public CompanyClassificationsId() {
	}

	public CompanyClassificationsId(long companyId, short classificationId) {
		this.companyId = companyId;
		this.classificationId = classificationId;
	}

	public long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(long companyId) {
		this.companyId = companyId;
	}

	public short getClassificationId() {
		return this.classificationId;
	}

	public void setClassificationId(short classificationId) {
		this.classificationId = classificationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CompanyClassificationsId))
			return false;
		CompanyClassificationsId castOther = (CompanyClassificationsId) other;

		return (this.getCompanyId() == castOther.getCompanyId())
				&& (this.getClassificationId() == castOther
						.getClassificationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCompanyId();
		result = 37 * result + this.getClassificationId();
		return result;
	}

}
