package com.pipegrid.model;

// Generated Aug 24, 2012 4:44:03 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CompanyClassificationLkup generated by hbm2java
 */
public class CompanyClassificationLkup implements java.io.Serializable {

	private short classificationId;
	private String name;
	private String description;
	private Set<CompanyClassifications> companyClassificationses = new HashSet<CompanyClassifications>(
			0);

	public CompanyClassificationLkup() {
	}

	public CompanyClassificationLkup(short classificationId, String name) {
		this.classificationId = classificationId;
		this.name = name;
	}

	public CompanyClassificationLkup(short classificationId, String name,
			String description,
			Set<CompanyClassifications> companyClassificationses) {
		this.classificationId = classificationId;
		this.name = name;
		this.description = description;
		this.companyClassificationses = companyClassificationses;
	}

	public short getClassificationId() {
		return this.classificationId;
	}

	public void setClassificationId(short classificationId) {
		this.classificationId = classificationId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<CompanyClassifications> getCompanyClassificationses() {
		return this.companyClassificationses;
	}

	public void setCompanyClassificationses(
			Set<CompanyClassifications> companyClassificationses) {
		this.companyClassificationses = companyClassificationses;
	}

}
