package com.pipegrid.model;

// Generated Aug 24, 2012 4:44:03 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * CompanyTypeLkup generated by hbm2java
 */
public class CompanyTypeLkup implements java.io.Serializable {

	private char companyTypeCode;
	private String name;
	private Set<Company> companies = new HashSet<Company>(0);

	public CompanyTypeLkup() {
	}

	public CompanyTypeLkup(char companyTypeCode, String name) {
		this.companyTypeCode = companyTypeCode;
		this.name = name;
	}

	public CompanyTypeLkup(char companyTypeCode, String name,
			Set<Company> companies) {
		this.companyTypeCode = companyTypeCode;
		this.name = name;
		this.companies = companies;
	}

	public char getCompanyTypeCode() {
		return this.companyTypeCode;
	}

	public void setCompanyTypeCode(char companyTypeCode) {
		this.companyTypeCode = companyTypeCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Company> getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}

}
