package com.pipegrid.model;

// Generated Aug 24, 2012 4:44:03 PM by Hibernate Tools 4.0.0

/**
 * ItemImages generated by hbm2java
 */
public class ItemImages implements java.io.Serializable {

	private long imageId;
	private Item item;
	private Lot lot;
	private String description;
	private byte[] data;

	public ItemImages() {
	}

	public ItemImages(long imageId, byte[] data) {
		this.imageId = imageId;
		this.data = data;
	}

	public ItemImages(long imageId, Item item, Lot lot, String description,
			byte[] data) {
		this.imageId = imageId;
		this.item = item;
		this.lot = lot;
		this.description = description;
		this.data = data;
	}

	public long getImageId() {
		return this.imageId;
	}

	public void setImageId(long imageId) {
		this.imageId = imageId;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Lot getLot() {
		return this.lot;
	}

	public void setLot(Lot lot) {
		this.lot = lot;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

}
