package com.pipegrid.model;

// Generated Aug 24, 2012 4:44:03 PM by Hibernate Tools 4.0.0

/**
 * ItemFiles generated by hbm2java
 */
public class ItemFiles implements java.io.Serializable {

	private long fileId;
	private Item item;
	private Lot lot;
	private String name;
	private String description;
	private String data;
	private String mimeType;
	private Integer size;

	public ItemFiles() {
	}

	public ItemFiles(long fileId, String name, String data) {
		this.fileId = fileId;
		this.name = name;
		this.data = data;
	}

	public ItemFiles(long fileId, Item item, Lot lot, String name,
			String description, String data, String mimeType, Integer size) {
		this.fileId = fileId;
		this.item = item;
		this.lot = lot;
		this.name = name;
		this.description = description;
		this.data = data;
		this.mimeType = mimeType;
		this.size = size;
	}

	public long getFileId() {
		return this.fileId;
	}

	public void setFileId(long fileId) {
		this.fileId = fileId;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Lot getLot() {
		return this.lot;
	}

	public void setLot(Lot lot) {
		this.lot = lot;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public String getMimeType() {
		return this.mimeType;
	}

	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	public Integer getSize() {
		return this.size;
	}

	public void setSize(Integer size) {
		this.size = size;
	}

}
