package com.pipegrid.model;

// Generated Aug 24, 2012 4:44:03 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * ItemPipe generated by hbm2java
 */
public class ItemPipe extends Persist {

	private Item item;
	private char pipeTypeCode;
	private BigDecimal outsideDiameterIn;
	private Long quantityFeet;
	private BigDecimal wallThicknessIn;
	private String coating;
	private BigDecimal weightLbsFt;

	public ItemPipe() {
	}

	public ItemPipe(Item item, char pipeTypeCode,
			BigDecimal outsideDiameterIn) {
		this.item = item;
		this.pipeTypeCode = pipeTypeCode;
		this.outsideDiameterIn = outsideDiameterIn;
	}

	public ItemPipe(Item item, char pipeTypeCode,
			BigDecimal outsideDiameterIn, Long quantityFeet,
			BigDecimal wallThicknessIn, String coating, BigDecimal weightLbsFt) {
		this.item = item;
		this.pipeTypeCode = pipeTypeCode;
		this.outsideDiameterIn = outsideDiameterIn;
		this.quantityFeet = quantityFeet;
		this.wallThicknessIn = wallThicknessIn;
		this.coating = coating;
		this.weightLbsFt = weightLbsFt;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public char getPipeTypeCode() {
		return this.pipeTypeCode;
	}

	public void setPipeTypeCode(char pipeTypeCode) {
		this.pipeTypeCode = pipeTypeCode;
	}

	public BigDecimal getOutsideDiameterIn() {
		return this.outsideDiameterIn;
	}

	public void setOutsideDiameterIn(BigDecimal outsideDiameterIn) {
		this.outsideDiameterIn = outsideDiameterIn;
	}

	public Long getQuantityFeet() {
		return this.quantityFeet;
	}

	public void setQuantityFeet(Long quantityFeet) {
		this.quantityFeet = quantityFeet;
	}

	public BigDecimal getWallThicknessIn() {
		return this.wallThicknessIn;
	}

	public void setWallThicknessIn(BigDecimal wallThicknessIn) {
		this.wallThicknessIn = wallThicknessIn;
	}

	public String getCoating() {
		return this.coating;
	}

	public void setCoating(String coating) {
		this.coating = coating;
	}

	public BigDecimal getWeightLbsFt() {
		return this.weightLbsFt;
	}

	public void setWeightLbsFt(BigDecimal weightLbsFt) {
		this.weightLbsFt = weightLbsFt;
	}

}
