package com.pipegrid.model;

// Generated Aug 24, 2012 4:44:03 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lot generated by hbm2java
 */
public class Lot implements java.io.Serializable {

	private long lotId;
	private User userByUpdateUserId;
	private Company company;
	private User userByCreateUserId;
	private String description;
	private Date createDate;
	private Date updateDate;
	private Date inactiveDate;
	private Boolean isPublic;
	private Set<ItemFiles> itemFileses = new HashSet<ItemFiles>(0);
	private Set<ItemImages> itemImageses = new HashSet<ItemImages>(0);
	private Set<Item> items = new HashSet<Item>(0);

	public Lot() {
	}

	public Lot(long lotId, User userByCreateUserId, Date createDate) {
		this.lotId = lotId;
		this.userByCreateUserId = userByCreateUserId;
		this.createDate = createDate;
	}

	public Lot(long lotId, User userByUpdateUserId, Company company,
			User userByCreateUserId, String description, Date createDate,
			Date updateDate, Date inactiveDate, Boolean isPublic,
			Set<ItemFiles> itemFileses, Set<ItemImages> itemImageses,
			Set<Item> items) {
		this.lotId = lotId;
		this.userByUpdateUserId = userByUpdateUserId;
		this.company = company;
		this.userByCreateUserId = userByCreateUserId;
		this.description = description;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.inactiveDate = inactiveDate;
		this.isPublic = isPublic;
		this.itemFileses = itemFileses;
		this.itemImageses = itemImageses;
		this.items = items;
	}

	public long getLotId() {
		return this.lotId;
	}

	public void setLotId(long lotId) {
		this.lotId = lotId;
	}

	public User getUserByUpdateUserId() {
		return this.userByUpdateUserId;
	}

	public void setUserByUpdateUserId(User userByUpdateUserId) {
		this.userByUpdateUserId = userByUpdateUserId;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public User getUserByCreateUserId() {
		return this.userByCreateUserId;
	}

	public void setUserByCreateUserId(User userByCreateUserId) {
		this.userByCreateUserId = userByCreateUserId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Date getInactiveDate() {
		return this.inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

	public Boolean getIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(Boolean isPublic) {
		this.isPublic = isPublic;
	}

	public Set<ItemFiles> getItemFileses() {
		return this.itemFileses;
	}

	public void setItemFileses(Set<ItemFiles> itemFileses) {
		this.itemFileses = itemFileses;
	}

	public Set<ItemImages> getItemImageses() {
		return this.itemImageses;
	}

	public void setItemImageses(Set<ItemImages> itemImageses) {
		this.itemImageses = itemImageses;
	}

	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

}
