package com.pipegrid.model;

// Generated Aug 24, 2012 4:44:03 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * StateLkup generated by hbm2java
 */
public class StateLkup implements java.io.Serializable {

	private String stateCode;
	private String name;
	private Set<Item> items = new HashSet<Item>(0);
	private Set<Company> companies = new HashSet<Company>(0);

	public StateLkup() {
	}

	public StateLkup(String stateCode, String name) {
		this.stateCode = stateCode;
		this.name = name;
	}

	public StateLkup(String stateCode, String name, Set<Item> items,
			Set<Company> companies) {
		this.stateCode = stateCode;
		this.name = name;
		this.items = items;
		this.companies = companies;
	}

	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Item> getItems() {
		return this.items;
	}

	public void setItems(Set<Item> items) {
		this.items = items;
	}

	public Set<Company> getCompanies() {
		return this.companies;
	}

	public void setCompanies(Set<Company> companies) {
		this.companies = companies;
	}

}
