package com.pipegrid.model;

// Generated Aug 24, 2012 4:44:03 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User extends Persist 
{

	private Company company;
	private RoleLkup roleLkup;
	private String username;
	private String password;
	private String firstName;
	private String lastName;
	private String title;
	private Date createDate;
	private Date inactiveDate;
	private Set<Item> itemsForUpdateUserId = new HashSet<Item>(0);
	private Set<Lot> lotsForCreateUserId = new HashSet<Lot>(0);
	private Set<Lot> lotsForUpdateUserId = new HashSet<Lot>(0);
	private Set<Item> itemsForCreateUserId = new HashSet<Item>(0);

	public User() {
	}

	public User(String username, String password, String firstName, String lastName) {
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public RoleLkup getRoleLkup() {
		return this.roleLkup;
	}

	public void setRoleLkup(RoleLkup roleLkup) {
		this.roleLkup = roleLkup;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getInactiveDate() {
		return this.inactiveDate;
	}

	public void setInactiveDate(Date inactiveDate) {
		this.inactiveDate = inactiveDate;
	}

	public Set<Item> getItemsForUpdateUserId() {
		return this.itemsForUpdateUserId;
	}

	public void setItemsForUpdateUserId(Set<Item> itemsForUpdateUserId) {
		this.itemsForUpdateUserId = itemsForUpdateUserId;
	}

	public Set<Lot> getLotsForCreateUserId() {
		return this.lotsForCreateUserId;
	}

	public void setLotsForCreateUserId(Set<Lot> lotsForCreateUserId) {
		this.lotsForCreateUserId = lotsForCreateUserId;
	}

	public Set<Lot> getLotsForUpdateUserId() {
		return this.lotsForUpdateUserId;
	}

	public void setLotsForUpdateUserId(Set<Lot> lotsForUpdateUserId) {
		this.lotsForUpdateUserId = lotsForUpdateUserId;
	}

	public Set<Item> getItemsForCreateUserId() {
		return this.itemsForCreateUserId;
	}

	public void setItemsForCreateUserId(Set<Item> itemsForCreateUserId) {
		this.itemsForCreateUserId = itemsForCreateUserId;
	}

}
